version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    environment:
      - DATABASE_URL=mongodb://mongo/f8_education_dev
    volumes:
      - ./:/code
    depends_on: 
      - mongo

  mongo:
    image: minhchien635/mongo_nodejsblog:lasted
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db 
volumes:
 mongodb: